server:
  port: 8083

spring:
  application:
    name: COURSE-SERVICE
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: course-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          CoachProfileChangedEvent:com.example.common.event.CoachProfileChangedEvent,
          CoursePurchasedEvent:com.example.common.event.CoursePurchasedEvent
  datasource:
    url: ${COURSE_DB_URL}
    username: ${COURSE_DB_USERNAME}
    password: ${COURSE_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB





jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true