server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
  application:
    name: USER-SERVICE

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.type.mapping: >
          CoachProfileChangedEvent:com.skillup.user_service.model.dto.CoachProfileChangedEvent

    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          CourseSaleCompletedEvent:com.example.common.event.CourseSaleCompletedEvent

  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    prefer-ip-address: true