services:
  postgres:
    image: postgres:15
    container_name: course-service-postgres
    restart: always

    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    ports:
      - "5435:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: